export interface ReplyContext {
  username: string;
  comment: string;
}

type ReplyFn = (ctx: ReplyContext) => string;

function pick(options: string[]): string {
  return options[Math.floor(Math.random() * options.length)];
}

function at(username: string): string {
  return username ? `@${username}` : "";
}

function atSpace(username: string): string {
  return username ? `@${username} ` : "";
}

const SPIRIT_ANIMALS = [
  "You clearly exhibit energetic, mischievous, nimble traits and thus your spirit animal is:\nA Monkey 🐒",
  "You clearly exhibit strong, protective, grounded traits and thus your spirit animal is:\nA Gorilla 🦍",
  "You clearly exhibit wise, gentle, contemplative traits and thus your spirit animal is:\nAn Orangutan 🦧",
  "You clearly exhibit active, devoted, reliable traits and thus your spirit animal is:\nA Dog 🐕",
  "You clearly exhibit helpful, steadfast, caring traits and thus your spirit animal is:\nA Guide Dog 🦮",
  "You clearly exhibit disciplined, attentive, supportive traits and thus your spirit animal is:\nA Service Dog 🐕‍🦺",
  "You clearly exhibit elegant, proud, intelligent traits and thus your spirit animal is:\nA Poodle 🐩",
  "You clearly exhibit independent, intuitive, fiercely loyal traits and thus your spirit animal is:\nA Wolf 🐺",
  "You clearly exhibit clever, adaptable, quick-witted traits and thus your spirit animal is:\nA Fox 🦊",
  "You clearly exhibit resourceful, curious, scrappy traits and thus your spirit animal is:\nA Raccoon 🦝",
  "You clearly exhibit aloof, agile, mysterious traits and thus your spirit animal is:\nA Cat 🐈",
  "You clearly exhibit mystical, intuitive, sleek traits and thus your spirit animal is:\nA Black Cat 🐈‍⬛",
  "You clearly exhibit courageous, regal, commanding traits and thus your spirit animal is:\nA Lion 🦁",
  "You clearly exhibit powerful, solitary, focused traits and thus your spirit animal is:\nA Tiger 🐅",
  "You clearly exhibit stealthy, ambitious, swift traits and thus your spirit animal is:\nA Leopard 🐆",
  "You clearly exhibit driven, energetic, untamed traits and thus your spirit animal is:\nA Horse 🐎",
  "You clearly exhibit magical, unique, pure traits and thus your spirit animal is:\nA Unicorn 🦄",
  "You clearly exhibit individualistic, social, striking traits and thus your spirit animal is:\nA Zebra 🦓",
  "You clearly exhibit gentle, sensitive, graceful traits and thus your spirit animal is:\nA Deer 🦌",
  "You clearly exhibit resilient, steady, powerful traits and thus your spirit animal is:\nA Bison 🦬",
  "You clearly exhibit imposing, solitary, majestic traits and thus your spirit animal is:\nA Moose 🫎",
  "You clearly exhibit stubborn, hardworking, reliable traits and thus your spirit animal is:\nA Donkey 🫏",
  "You clearly exhibit hardworking, determined, steadfast traits and thus your spirit animal is:\nAn Ox 🐂",
  "You clearly exhibit enduring, robust, calm traits and thus your spirit animal is:\nA Water Buffalo 🐃",
  "You clearly exhibit peaceful, grounded, providing traits and thus your spirit animal is:\nA Cow 🐄",
  "You clearly exhibit resourceful, relaxed, friendly traits and thus your spirit animal is:\nA Pig 🐖",
  "You clearly exhibit courageous, assertive, untamed traits and thus your spirit animal is:\nA Boar 🐗",
  "You clearly exhibit curious, quirky, perceptive traits and thus your spirit animal is:\nA Pig Nose 🐽",
  "You clearly exhibit headstrong, determined, confident traits and thus your spirit animal is:\nA Ram 🐏",
  "You clearly exhibit gentle, compliant, harmonious traits and thus your spirit animal is:\nA Sheep 🐑",
  "You clearly exhibit agile, curious, persistent traits and thus your spirit animal is:\nA Goat 🐐",
  "You clearly exhibit resilient, patient, enduring traits and thus your spirit animal is:\nA Camel 🐪",
  "You clearly exhibit prepared, adaptable, steady traits and thus your spirit animal is:\nA Two-Hump Camel 🐫",
  "You clearly exhibit quirky, proud, expressive traits and thus your spirit animal is:\nA Llama 🦙",
  "You clearly exhibit visionary, elegant, far-sighted traits and thus your spirit animal is:\nA Giraffe 🦒",
  "You clearly exhibit wise, empathetic, unforgetting traits and thus your spirit animal is:\nAn Elephant 🐘",
  "You clearly exhibit ancient, mighty, enduring traits and thus your spirit animal is:\nA Mammoth 🦣",
  "You clearly exhibit grounded, assertive, tough traits and thus your spirit animal is:\nA Rhinoceros 🦏",
  "You clearly exhibit powerful, territorial, unexpectedly swift traits and thus your spirit animal is:\nA Hippopotamus 🦛",
  "You clearly exhibit timid, quick, observant traits and thus your spirit animal is:\nA Mouse 🐁",
  "You clearly exhibit highly intelligent, adaptable, survivor traits and thus your spirit animal is:\nA Rat 🐀",
  "You clearly exhibit energetic, cute, busy traits and thus your spirit animal is:\nA Hamster 🐹",
  "You clearly exhibit peaceful, quiet, nimble traits and thus your spirit animal is:\nA Rabbit 🐇",
  "You clearly exhibit prepared, energetic, busy traits and thus your spirit animal is:\nA Chipmunk 🐿️",
  "You clearly exhibit industrious, constructive, focused traits and thus your spirit animal is:\nA Beaver 🦫",
  "You clearly exhibit defensive, cautious, adorable traits and thus your spirit animal is:\nA Hedgehog 🦔",
  "You clearly exhibit intuitive, nocturnal, misunderstood traits and thus your spirit animal is:\nA Bat 🦇",
  "You clearly exhibit strong, protective, introspective traits and thus your spirit animal is:\nA Bear 🐻",
  "You clearly exhibit resilient, fierce, solitary traits and thus your spirit animal is:\nA Polar Bear 🐻‍❄️",
  "You clearly exhibit relaxed, peaceful, easygoing traits and thus your spirit animal is:\nA Koala 🐨",
  "You clearly exhibit gentle, peaceful, balanced traits and thus your spirit animal is:\nA Panda 🐼",
  "You clearly exhibit deliberate, relaxed, unhurried traits and thus your spirit animal is:\nA Sloth 🦥",
  "You clearly exhibit playful, joyful, communal traits and thus your spirit animal is:\nAn Otter 🦦",
  "You clearly exhibit boundaried, confident, distinctive traits and thus your spirit animal is:\nA Skunk 🦨",
  "You clearly exhibit forward-moving, protective, energetic traits and thus your spirit animal is:\nA Kangaroo 🦘",
  "You clearly exhibit fierce, determined, fearless traits and thus your spirit animal is:\nA Badger 🦡",
  "You clearly exhibit abundant, communal, proud traits and thus your spirit animal is:\nA Turkey 🦃",
  "You clearly exhibit social, vocal, domestic traits and thus your spirit animal is:\nA Chicken 🐔",
  "You clearly exhibit punctual, confident, showy traits and thus your spirit animal is:\nA Rooster 🐓",
  "You clearly exhibit emerging, new, vulnerable traits and thus your spirit animal is:\nA Hatching Chick 🐣",
  "You clearly exhibit innocent, optimistic, fresh traits and thus your spirit animal is:\nA Baby Chick 🐤",
  "You clearly exhibit curious, bright, endearing traits and thus your spirit animal is:\nA Front-Facing Chick 🐥",
  "You clearly exhibit free, communicative, observant traits and thus your spirit animal is:\nA Bird 🐦",
  "You clearly exhibit dedicated, social, adaptable traits and thus your spirit animal is:\nA Penguin 🐧",
  "You clearly exhibit peaceful, pure, hopeful traits and thus your spirit animal is:\nA Dove 🕊️",
  "You clearly exhibit visionary, powerful, majestic traits and thus your spirit animal is:\nAn Eagle 🦅",
  "You clearly exhibit adaptable, buoyant, humorous traits and thus your spirit animal is:\nA Duck 🦆",
  "You clearly exhibit elegant, graceful, devoted traits and thus your spirit animal is:\nA Swan 🦢",
  "You clearly exhibit wise, observant, intuitive traits and thus your spirit animal is:\nAn Owl 🦉",
  "You clearly exhibit quirky, unique, trusting traits and thus your spirit animal is:\nA Dodo 🦤",
  "You clearly exhibit vibrant, balanced, social traits and thus your spirit animal is:\nA Flamingo 🦩",
  "You clearly exhibit expressive, proud, colorful traits and thus your spirit animal is:\nA Peacock 🦚",
  "You clearly exhibit communicative, vibrant, mimic traits and thus your spirit animal is:\nA Parrot 🦜",
  "You clearly exhibit mysterious, intelligent, vocal traits and thus your spirit animal is:\nA Blackbird 🐦‍⬛",
  "You clearly exhibit territorial, communicative, loyal traits and thus your spirit animal is:\nA Goose 🪿",
  "You clearly exhibit reborn, fiery, resilient traits and thus your spirit animal is:\nA Phoenix 🐦‍🔥",
  "You clearly exhibit transformative, vocal, adaptive traits and thus your spirit animal is:\nA Frog 🐸",
  "You clearly exhibit ancient, patient, formidable traits and thus your spirit animal is:\nA Crocodile 🐊",
  "You clearly exhibit steady, protected, unhurried traits and thus your spirit animal is:\nA Turtle 🐢",
  "You clearly exhibit adaptable, quick, regenerative traits and thus your spirit animal is:\nA Lizard 🦎",
  "You clearly exhibit transformative, intuitive, shedding traits and thus your spirit animal is:\nA Snake 🐍",
  "You clearly exhibit powerful, ancient, majestic traits and thus your spirit animal is:\nA Dragon 🐉",
  "You clearly exhibit gentle, massive, ancient traits and thus your spirit animal is:\nA Sauropod 🦕",
  "You clearly exhibit dominant, fierce, legendary traits and thus your spirit animal is:\nA T-Rex 🦖",
  "You clearly exhibit expressive, massive, emotional traits and thus your spirit animal is:\nA Spouting Whale 🐳",
  "You clearly exhibit deep, ancient, soulful traits and thus your spirit animal is:\nA Whale 🐋",
  "You clearly exhibit intelligent, playful, harmonious traits and thus your spirit animal is:\nA Dolphin 🐬",
  "You clearly exhibit playful, adaptable, smooth traits and thus your spirit animal is:\nA Seal 🦭",
  "You clearly exhibit flowing, adaptive, communal traits and thus your spirit animal is:\nA Fish 🐟",
  "You clearly exhibit vibrant, unique, lively traits and thus your spirit animal is:\nA Tropical Fish 🐠",
  "You clearly exhibit defensive, surprising, unique traits and thus your spirit animal is:\nA Blowfish 🐡",
  "You clearly exhibit driven, sleek, focused traits and thus your spirit animal is:\nA Shark 🦈",
  "You clearly exhibit highly intelligent, adaptable, multi-tasking traits and thus your spirit animal is:\nAn Octopus 🐙",
  "You clearly exhibit mysterious, flexible, elusive traits and thus your spirit animal is:\nA Squid 🦑",
  "You clearly exhibit flowing, transparent, stinging traits and thus your spirit animal is:\nA Jellyfish 🪼",
  "You clearly exhibit small, resilient, swift traits and thus your spirit animal is:\nA Shrimp 🦐",
  "You clearly exhibit shielded, complex, enduring traits and thus your spirit animal is:\nA Lobster 🦞",
  "You clearly exhibit protective, sideways-thinking, tough traits and thus your spirit animal is:\nA Crab 🦀",
  "You clearly exhibit patient, unhurried, homebound traits and thus your spirit animal is:\nA Snail 🐌",
  "You clearly exhibit graceful, transformative, colorful traits and thus your spirit animal is:\nA Butterfly 🦋",
  "You clearly exhibit transformative, patient, hungry traits and thus your spirit animal is:\nA Bug 🐛",
  "You clearly exhibit hardworking, communal, strong traits and thus your spirit animal is:\nAn Ant 🐜",
  "You clearly exhibit industrious, sweet, collaborative traits and thus your spirit animal is:\nA Honeybee 🐝",
  "You clearly exhibit grounded, resilient, armored traits and thus your spirit animal is:\nA Beetle 🪲",
  "You clearly exhibit lucky, bright, delicate traits and thus your spirit animal is:\nA Ladybug 🐞",
  "You clearly exhibit musical, leaping, nocturnal traits and thus your spirit animal is:\nA Cricket 🦗",
  "You clearly exhibit invincible, adaptable, survivor traits and thus your spirit animal is:\nA Cockroach 🪳",
  "You clearly exhibit creative, patient, weaving traits and thus your spirit animal is:\nA Spider 🕷️",
  "You clearly exhibit defensive, intense, cautious traits and thus your spirit animal is:\nA Scorpion 🦂",
  "You clearly exhibit persistent, parasitic, buzzing traits and thus your spirit animal is:\nA Mosquito 🦟",
  "You clearly exhibit persistent, annoying, fast traits and thus your spirit animal is:\nA Fly 🪰",
  "You clearly exhibit humble, regenerative, grounded traits and thus your spirit animal is:\nA Worm 🪱"
];

const FORTUNES = [
  "A pleasant surprise is heading your way much sooner than you think.",
  "Trust your gut feeling, it is sharper than you give it credit for.",
  "Good things truly come to those who work hard and wait patiently.",
  "The massive amount of effort you have been putting in lately is about to pay off in a big way.",
  "A brand new door is about to swing open for you; be ready to walk through it.",
  "A simple smile can change the entire energy of your day, try it out.",
  "You are actually much closer to your goal than you realize right now.",
  "Fortune loves to favor the bold, so do not be afraid to take that leap today.",
  "Keep pushing forward; the momentum you have built is far stronger than any obstacle.",
  "A truly delightful surprise is waiting for you just around the corner.",
  "Do not resist the change that is coming; it is the catalyst you have been needing.",
  "Your genuine kindness towards others will return to you tenfold very soon.",
  "A grand adventure is calling your name, pack your bags or just your mindset.",
  "Trust the unique, winding path of your life; it is leading exactly where it should.",
  "A deep and meaningful connection is currently forming in your life.",
  "Great, sustained success is waiting in your future, so keep building.",
  "Stay curious, keep exploring, and never lose your sense of wonder.",
  "Your creative spirit is the key that will unlock doors you thought were locked.",
  "Happiness is not just a goal; it is your natural state when you let go of the noise.",
  "A hidden, secret talent of yours is about to emerge and surprise everyone.",
  "Take that calculated risk you have been thinking about, the payoff will be worth it.",
  "Deep, lasting peace is going to find you after this current storm passes.",
  "Your unique perspective is your greatest power; do not let anyone dull it.",
  "Keep your eyes peeled, because you should definitely expect the unexpected today.",
  "Remember that even the smallest, most insignificant steps lead to the biggest wins.",
  "Believe in your own vision, even when nobody else seems to see it yet.",
  "Someone is thinking of you with a lot of warmth and admiration right now.",
  "A dream you have been holding onto for years is finally becoming your reality.",
  "You have significantly more inner strength than this current situation requires.",
  "The clouds are parting, and clear, bright skies are ahead for you.",
  "Your voice carries weight; do not be afraid to speak your truth loudly.",
  "Today is a perfect day for action, stop planning and start executing.",
  "Luck is not just fate; it is preparation meeting opportunity, and you are ready.",
  "Stop looking for the big highlights and start finding joy in the quiet, small things.",
  "A new friend who shares your vision is about to enter your life.",
  "Let go of whatever is holding you back, it was never meant to be part of your future.",
  "Success is something you build brick by brick, not something you are just handed.",
  "You are doing so much better than you give yourself credit for.",
  "Take a long, deep breath and just let the stress evaporate for a moment.",
  "A massive, game-changing opportunity is currently making its way to your desk.",
  "That nagging intuition you have been having lately? It is completely spot on.",
  "Some genuinely great news is currently en route to your inbox.",
  "You are quite literally destined for greatness, provided you keep showing up.",
  "Stay true to your own path, even if it feels lonely sometimes.",
  "A very positive change is starting to ripple through your life right now.",
  "Courage does not mean having no fear, it means moving forward anyway.",
  "Listen twice as much as you speak today, and you will learn something valuable.",
  "Your future looks brighter than you can possibly imagine.",
  "Do not for a second doubt the abilities you have worked so hard to develop.",
  "Expect a truly delightful surprise that will leave you grinning.",
  "Patience is a superpower; it brings the rewards that rush can never touch.",
  "The hard work you have put in behind the scenes is finally being noticed.",
  "Focus ruthlessly on what truly matters and ignore the background noise.",
  "You will master this challenge; it is just another stepping stone for you.",
  "Kindness is the ultimate master key that opens every locked door.",
  "Your energy is incredibly contagious today, use it to lift others up.",
  "A massive creative spark is about to ignite; have a notebook ready.",
  "Stay flexible like the willow, and you will survive any wind.",
  "You are entirely worthy of the success you are striving for.",
  "A dream you thought had withered is about to bloom beautifully.",
  "Trust the process, even when the middle parts feel messy.",
  "Keep asking the right questions, and you will definitely find the answers.",
  "Today is absolutely packed with untapped possibilities waiting for you.",
  "An old friend you have not thought about in a while will reach out.",
  "Your confidence is quietly increasing every single day you work on yourself.",
  "Do not wait for luck, make your own today with sheer willpower.",
  "You are on the right track, even if the progress feels slow.",
  "Peace will follow your every step, provided you choose to carry it.",
  "Something very special is happening beneath the surface of your life.",
  "Your light is meant to shine bright, stop trying to dim it for others.",
  "Stand tall, because you are ready for whatever comes next.",
  "Some great, life-changing wisdom will come to you in a quiet moment.",
  "A change of heart might be the best thing that happens to you all year.",
  "Embrace your inner strength; it is the foundation of your future.",
  "Good fortune tends to follow those who lead with honesty.",
  "You have a hidden ally you do not even know about yet.",
  "Everything is falling into place, even the pieces that seem random right now.",
  "Take a leap of faith, the net will appear once you jump.",
  "Your dedication is quietly inspiring everyone around you to work harder.",
  "A very simple joy is waiting for you later today, do not miss it.",
  "Stay focused like a laser on your primary goal this week.",
  "You already have everything you need to solve this problem.",
  "A completely new chapter is beginning, get ready to write a great story.",
  "Always look for the silver lining, it is there, I promise.",
  "You will succeed with ease if you stop overcomplicating things.",
  "Wisdom is not just knowing things; it is the experience of having lived through them.",
  "Keep your spirits high today, no matter what happens.",
  "An exciting path is opening up, have you noticed it yet?",
  "Believe in your full potential, you are capable of more than you think.",
  "Happiness is an inside job, and you are the CEO.",
  "You are making much greater progress than you realize.",
  "A wonderful surprise is near, try to stay present so you do not miss it.",
  "Your vision is slowly but surely becoming your reality.",
  "Trust your inner compass; it knows exactly where north is.",
  "Great rewards are coming to you as a result of your consistency.",
  "Stay positive and keep shining your light, the world needs it.",
  "You have some of your best, most profitable ideas today.",
  "Success is waiting just for you; it just needs you to show up.",
  "A new venture or project will bring you more joy than you expect.",
  "Everything is working out fine, take a load off and relax."
];

// Add your custom comment reply functions here.
// Each function receives context about the comment and commenter.
export const commentReplyFunctions: Record<string, ReplyFn> = {
  hype_replies: ({ username }) =>
    pick([
      `Let's go ${at(username)}! 🔥 Check your DMs!`,
      `Yesss ${at(username)}! Sending it over now 🚀`,
      `${atSpace(username)}omg yes!! Just DM'd you 🙌`,
      `Already on it ${at(username)} 👀 check your DMs!`,
    ]),

  soft_replies: ({ username }) =>
    pick([
      `Hey ${at(username)}, just sent you something 💌`,
      `Check your DMs ${at(username)}! 🤍`,
      `Sent it over ${at(username)} ✨`,
      `Just DM'd you the details ${at(username)} 🫶`,
    ]),

  casual_replies: ({ username }) =>
    pick([
      `${atSpace(username)}check your DMs! 📩`,
      `Sent you a DM ${at(username)}!`,
      `Just DM'd you ${at(username)} 👌`,
      `Got you ${at(username)} — check your DMs!`,
    ]),

  spirit_animal: ({ username }) =>
    `${atSpace(username)}${pick(SPIRIT_ANIMALS)}`,

  fortune_cookie: ({ username }) =>
    `${atSpace(username)}🥠 ${pick(FORTUNES)}`,
};

export function callReplyFunction(name: string, ctx: ReplyContext): string | null {
  const fn = commentReplyFunctions[name];
  return fn ? fn(ctx) : null;
}

export function listReplyFunctions(): Array<{ name: string; preview: string }> {
  return Object.entries(commentReplyFunctions).map(([name, fn]) => ({
    name,
    preview: fn({ username: "username", comment: "" }),
  }));
}